import { defineConfig, globalIgnores } from 'eslint/config'
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

export default defineConfig([
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      // The rendering layer deliberately treats Payload docs as `any`
      // (see src/lib/types.ts) — enforcing this rule would fight that pattern.
      '@typescript-eslint/no-explicit-any': 'off',
      // Allow the destructure-to-omit pattern ({ omitted, ...rest }).
      '@typescript-eslint/no-unused-vars': ['warn', { ignoreRestSiblings: true }],
      // New in eslint-plugin-react-hooks v7. The codebase is clean of both:
      // hydration "mounted" flags go through useSyncExternalStore (see
      // src/lib/hooks.ts) and previous-value tracking adjusts state during
      // render instead of reading refs. Keep it that way.
      'react-hooks/set-state-in-effect': 'error',
      'react-hooks/refs': 'error',
    },
  },
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by Payload — not hand-edited
    'src/app/(payload)/admin/importMap.js',
    'src/migrations/**',
    'src/payload-types.ts',
  ]),
])
