// Declares static image imports (*.webp, *.png, …) as StaticImageData.
// These types normally come from `next-env.d.ts`, but that file is gitignored
// and only regenerated by `next build` — so it's absent when CI runs
// `pnpm typecheck` *before* the build. This tracked reference makes the
// hero-carousel webp imports type-check in CI. (References the same types file
// next-env.d.ts does, so it dedupes when both are present during the build.)
/// <reference types="next/image-types/global" />
