/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    locations: Location;
    'team-members': TeamMember;
    events: Event;
    'journal-posts': JournalPost;
    quotes: Quote;
    faqs: Faq;
    partners: Partner;
    'daily-menus': DailyMenu;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'daily-menus': DailyMenusSelect<false> | DailyMenusSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility. Leave empty for decorative images.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Photo credit / attribution (optional)
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, e.g. "about" or "locations/wellington"
   */
  slug: string;
  /**
   * Page sections. Add a Hero first, then stack content blocks beneath.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            /**
             * Main H1. Newlines render as line breaks. Wrap a word in *asterisks* to italicise it.
             */
            heading: string;
            /**
             * Optional. A single word from the heading that gets the sun-yellow underline (case-sensitive, first match).
             */
            highlightWord?: string | null;
            subheading?: string | null;
            image?: (number | null) | Media;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Optional ghost-style link beside the primary CTA
             */
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            /**
             * Optional floating yellow circle sticker overlapping the hero image
             */
            sticker?: {
              /**
               * Each line renders separately. Wrap a word in *asterisks* to italicise it. Leave blank for no sticker.
               */
              text?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* for italic.
             */
            heading: string;
            subheading?: string | null;
            panelLabel?: string | null;
            amounts?:
              | {
                  /**
                   * e.g. 20 (whole dollars)
                   */
                  amount: number;
                  /**
                   * e.g. "1 meal"
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            ctaLabel?: string | null;
            /**
             * Optional. Falls back to Site Settings → donateUrl.
             */
            ctaHref?: string | null;
            footnote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'donateHero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('tight' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            aspect?: ('16:8' | '16:9' | '4:3' | '1:1' | 'auto') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* for italic.
             */
            heading?: string | null;
            variant?: ('light' | 'darkPanel') | null;
            source?: ('global' | 'custom') | null;
            items?:
              | {
                  /**
                   * e.g. "350,000"
                   */
                  value: string;
                  /**
                   * e.g. "meals served"
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'marquee';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* for italic.
             */
            heading?: string | null;
            items?:
              | {
                  /**
                   * e.g. "2017" or "Today"
                   */
                  year: string;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            eyebrow?: string | null;
            /**
             * Optional. Wrap a word in *asterisks* for italic.
             */
            heading?: string | null;
            /**
             * Optional CTA next to the heading (e.g. "Become a partner →")
             */
            viewAllLabel?: string | null;
            viewAllHref?: string | null;
            columns?: ('2' | '3' | '4') | null;
            /**
             * Visual treatment for the card backgrounds
             */
            cardStyle?: ('soft' | 'tile' | 'mixed') | null;
            items?:
              | {
                  /**
                   * e.g. "01"
                   */
                  number?: string | null;
                  title: string;
                  copy?: string | null;
                  /**
                   * Optional. Renders as mailto link below the copy.
                   */
                  email?: string | null;
                  ctaLabel?: string | null;
                  href?: string | null;
                  /**
                   * Used only when Card style = Per-card colours
                   */
                  color?: ('cream' | 'sun' | 'clay' | 'forest100' | 'forest700') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* to italicise it.
             */
            heading?: string | null;
            theme?: ('forest' | 'cream') | null;
            items?:
              | {
                  /**
                   * e.g. "01"
                   */
                  number?: string | null;
                  title: string;
                  copy?: string | null;
                  ctaLabel?: string | null;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pillars';
          }
        | {
            /**
             * Wrap a word in *asterisks* for italic.
             */
            heading: string;
            body?: string | null;
            variant?: ('sun' | 'forest') | null;
            align?: ('left' | 'center') | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaStrip';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* to italicise it.
             */
            heading?: string | null;
            /**
             * Optional CTA next to the heading, e.g. "All locations →"
             */
            viewAllLabel?: string | null;
            viewAllHref?: string | null;
            /**
             * Maximum number of locations to show
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'locationsGrid';
          }
        | {
            /**
             * Renders all locations as an alternating magazine-style list. Use the simpler "Locations grid" block for the home-page card layout.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'locationsMagazine';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* to italicise it.
             */
            heading?: string | null;
            viewAllLabel?: string | null;
            viewAllHref?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventsList';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* to italicise it.
             */
            heading?: string | null;
            viewAllLabel?: string | null;
            viewAllHref?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'journalList';
          }
        | {
            /**
             * Optional caption shown beneath the heading on the parent page. The block itself renders all team-members grouped by staff type.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamGrid';
          }
        | {
            /**
             * Optional caption. The block renders all FAQs from the collection, grouped by category.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqsAccordion';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* for italic.
             */
            heading?: string | null;
            viewAllLabel?: string | null;
            viewAllHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnersGrid';
          }
        | {
            footnote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterForm';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * e.g. "wellington", "onehunga", "glen-innes"
   */
  slug: string;
  openStatus?: ('open' | 'coming-soon' | 'closed') | null;
  /**
   * One-line description shown on cards
   */
  tagline?: string | null;
  intro?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  city?: string | null;
  address?: string | null;
  /**
   * Map pin (decimal degrees)
   */
  coordinates?: {
    /**
     * Latitude
     */
    lat?: number | null;
    /**
     * Longitude
     */
    lng?: number | null;
  };
  hours?:
    | {
        /**
         * e.g. "Wed – Sat"
         */
        label?: string | null;
        /**
         * e.g. "5pm – 9pm"
         */
        times?: string | null;
        /**
         * e.g. "Last seating 8.30pm"
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Direct booking link for this location
   */
  bookingUrl?: string | null;
  /**
   * Stripe / payment link
   */
  payAtTableUrl?: string | null;
  quotes?: (number | Quote)[] | null;
  highlights?:
    | {
        label: string;
        /**
         * e.g. "12,000 meals served"
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Defaults to page title
     */
    title?: string | null;
    /**
     * Aim for ~155 characters
     */
    description?: string | null;
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  /**
   * Stable identifier — e.g. "wellington-diner-2024"
   */
  slug: string;
  quote: string;
  /**
   * e.g. "Diner, Wellington" or a person's name
   */
  attribution: string;
  /**
   * Optional — used to surface this quote on that location's page
   */
  location?: (number | null) | Location;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  slug: string;
  jobTitle?: string | null;
  staffType?: ('board' | 'leadership' | 'kitchen' | 'foh' | 'operations' | 'volunteer') | null;
  /**
   * Lower numbers appear first
   */
  displayOrder?: number | null;
  profilePicture?: (number | null) | Media;
  bioSummary?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    twitter?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  slug: string;
  date: string;
  /**
   * Human-readable time, e.g. "6:00pm — 9:00pm"
   */
  displayTime?: string | null;
  location?: (number | null) | Location;
  image?: (number | null) | Media;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tickets?: {
    /**
     * e.g. "$95 per person"
     */
    priceLabel?: string | null;
    ticketUrl?: string | null;
    /**
     * Small print below the CTA
     */
    caption?: string | null;
  };
  seo?: {
    /**
     * Defaults to page title
     */
    title?: string | null;
    /**
     * Aim for ~155 characters
     */
    description?: string | null;
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  title: string;
  slug: string;
  category?: ('story' | 'news' | 'recipe' | 'behind-the-scenes' | 'impact') | null;
  summary?: string | null;
  mainImage?: (number | null) | Media;
  author?: string | null;
  authorMember?: (number | null) | TeamMember;
  publishedAt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * Defaults to page title
     */
    title?: string | null;
    /**
     * Aim for ~155 characters
     */
    description?: string | null;
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('pay-as-you-feel' | 'about-us' | 'dining' | 'volunteering' | 'donating' | 'our-meals' | 'events') | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  slug: string;
  tier: 'platinum' | 'gold' | 'funding' | 'supporting' | 'hospitality' | 'food';
  logo?: (number | null) | Media;
  url?: string | null;
  description?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-menus".
 */
export interface DailyMenu {
  id: number;
  /**
   * Auto-generated from date if blank
   */
  name: string;
  slug: string;
  menuDate: string;
  location?: (number | null) | Location;
  chefName?: string | null;
  courses?: {
    starter?: string | null;
    mainMeat?: string | null;
    mainVeg?: string | null;
    vegOnly?: boolean | null;
    dessert?: string | null;
    drink?: string | null;
  };
  announcement?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'daily-menus';
        value: number | DailyMenu;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              highlightWord?: T;
              subheading?: T;
              image?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              sticker?:
                | T
                | {
                    text?: T;
                  };
              id?: T;
              blockName?: T;
            };
        donateHero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              panelLabel?: T;
              amounts?:
                | T
                | {
                    amount?: T;
                    label?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              footnote?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              image?: T;
              aspect?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              variant?: T;
              source?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        marquee?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              viewAllLabel?: T;
              viewAllHref?: T;
              columns?: T;
              cardStyle?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    copy?: T;
                    email?: T;
                    ctaLabel?: T;
                    href?: T;
                    color?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pillars?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              theme?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    copy?: T;
                    ctaLabel?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaStrip?:
          | T
          | {
              heading?: T;
              body?: T;
              variant?: T;
              align?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        locationsGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              viewAllLabel?: T;
              viewAllHref?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        locationsMagazine?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        eventsList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              viewAllLabel?: T;
              viewAllHref?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        journalList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              viewAllLabel?: T;
              viewAllHref?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              caption?: T;
              id?: T;
              blockName?: T;
            };
        faqsAccordion?:
          | T
          | {
              caption?: T;
              id?: T;
              blockName?: T;
            };
        partnersGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              viewAllLabel?: T;
              viewAllHref?: T;
              id?: T;
              blockName?: T;
            };
        newsletterForm?:
          | T
          | {
              footnote?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  openStatus?: T;
  tagline?: T;
  intro?: T;
  body?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  city?: T;
  address?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  hours?:
    | T
    | {
        label?: T;
        times?: T;
        note?: T;
        id?: T;
      };
  phone?: T;
  email?: T;
  bookingUrl?: T;
  payAtTableUrl?: T;
  quotes?: T;
  highlights?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  jobTitle?: T;
  staffType?: T;
  displayOrder?: T;
  profilePicture?: T;
  bioSummary?: T;
  bio?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        twitter?: T;
        facebook?: T;
        linkedin?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  date?: T;
  displayTime?: T;
  location?: T;
  image?: T;
  shortDescription?: T;
  description?: T;
  tickets?:
    | T
    | {
        priceLabel?: T;
        ticketUrl?: T;
        caption?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  summary?: T;
  mainImage?: T;
  author?: T;
  authorMember?: T;
  publishedAt?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  slug?: T;
  quote?: T;
  attribution?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tier?: T;
  logo?: T;
  url?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-menus_select".
 */
export interface DailyMenusSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  menuDate?: T;
  location?: T;
  chefName?: T;
  courses?:
    | T
    | {
        starter?: T;
        mainMeat?: T;
        mainVeg?: T;
        vegOnly?: T;
        dessert?: T;
        drink?: T;
      };
  announcement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  description?: string | null;
  /**
   * Logo for dark backgrounds (white version)
   */
  logoLight?: (number | null) | Media;
  /**
   * Logo for light backgrounds (dark version)
   */
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * Default social-share image
   */
  ogImage?: (number | null) | Media;
  contactEmail?: string | null;
  pressEmail?: string | null;
  volunteerEmail?: string | null;
  phone?: string | null;
  charityNumber?: string | null;
  mailingAddress?: string | null;
  /**
   * Default booking link if a location doesn't have its own
   */
  bookingUrl?: string | null;
  donateUrl?: string | null;
  /**
   * External volunteer portal
   */
  volunteerUrl?: string | null;
  shopUrl?: string | null;
  social?:
    | {
        platform: 'instagram' | 'facebook' | 'linkedin' | 'tiktok' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Headline impact numbers used in the hero + footer
   */
  stats?:
    | {
        /**
         * e.g. "350,000"
         */
        value: string;
        /**
         * e.g. "meals served"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Main nav (3–4 items max)
   */
  primary?:
    | {
        link?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          /**
           * Path on this site, e.g. /our-story
           */
          internalHref?: string | null;
          /**
           * Full URL incl. https://
           */
          externalHref?: string | null;
          openInNewTab?: boolean | null;
        };
        /**
         * Shown on the right side of the overlay menu when this link is hovered (desktop only).
         */
        previewImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Secondary nav inside the drawer / footer
   */
  secondary?:
    | {
        link?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          /**
           * Path on this site, e.g. /our-story
           */
          internalHref?: string | null;
          /**
           * Full URL incl. https://
           */
          externalHref?: string | null;
          openInNewTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  ctas?: {
    bookLabel?: string | null;
    donateLabel?: string | null;
    shopLabel?: string | null;
    showShop?: boolean | null;
    volunteerLabel?: string | null;
    showVolunteer?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  /**
   * Up to 4 link columns
   */
  columns?:
    | {
        heading: string;
        links?:
          | {
              link?: {
                label?: string | null;
                type?: ('internal' | 'external') | null;
                /**
                 * Path on this site, e.g. /our-story
                 */
                internalHref?: string | null;
                /**
                 * Full URL incl. https://
                 */
                externalHref?: string | null;
                openInNewTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        link?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          /**
           * Path on this site, e.g. /our-story
           */
          internalHref?: string | null;
          /**
           * Full URL incl. https://
           */
          externalHref?: string | null;
          openInNewTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Year is appended automatically
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  logoLight?: T;
  logoDark?: T;
  favicon?: T;
  ogImage?: T;
  contactEmail?: T;
  pressEmail?: T;
  volunteerEmail?: T;
  phone?: T;
  charityNumber?: T;
  mailingAddress?: T;
  bookingUrl?: T;
  donateUrl?: T;
  volunteerUrl?: T;
  shopUrl?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              internalHref?: T;
              externalHref?: T;
              openInNewTab?: T;
            };
        previewImage?: T;
        id?: T;
      };
  secondary?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              internalHref?: T;
              externalHref?: T;
              openInNewTab?: T;
            };
        id?: T;
      };
  ctas?:
    | T
    | {
        bookLabel?: T;
        donateLabel?: T;
        shopLabel?: T;
        showShop?: T;
        volunteerLabel?: T;
        showVolunteer?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    internalHref?: T;
                    externalHref?: T;
                    openInNewTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              internalHref?: T;
              externalHref?: T;
              openInNewTab?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}